design-documents/allowed-http-methods-for-actions.md

Limit actions to processing only requests with certain HTTP methods in a declarative way

Allowed HTTP Methods for Actions

---

proposals/declarative-theme-media-breakpoints.md

Currently we declare theme breakpoints through LESS variables, notably `@screen__m` declares the breakpoint at which the design should change to a mobile design.
Page Builder requires more dynamic generation of styles due to the dynamic nature of how the content is created. We have background image functionality which requires the generation of CSS to provide a high performant solution, due to this we need to be able to determine the current themes mobile breakpoint.

[Proposal] Declarative Theme Media Breakpoints

---

README.md

1. Removed "proposals" folder, as `proposal` == `PR`, but the result is a design document, so everything should go to the Design Documents folder eventually.
1. Fixes https://github.com/magento/architecture/issues/22
1. Added process for PRs that need update after feedback.

Removed "proposals" folder

---

design-documents/sessions-only-for-html.md

It is unsafe to use sessions anywhere but controllers and blocks due to multiple web APIs in Magento

Sessions to be used only in controllers and blocks

---

design-documents/automated-config-file-cache.md

Every time a configuration file (any xml file) or Service contract is created/edited/removed in Magento, the corresponding configuration cache has to be cleared manually. This degrades developer experience, and makes invalidations more expensive as all configuration types are reloaded when config cache is cleared.
External solutions for automated cache invalidation exist:
- PHPStorm allows to configure a command to be executed whenever a file changes.
- https://github.com/mage2tv/magento-cache-clean - IDE agnostic solution by [Vinai](https://github.com/Vinai|Vinai)
To improve developer experience without reliance on external tools and additional setup, the approach similar to Opcache can be used:
- When configuration is written to cache, in addition to content, also write the names of …

Automated configuration file cache invalidation

---

design-documents/soap_operation_alias.md

Design document for improving consistency between RESTful and SOAP gateways

Allowing alias for SOAP operations

---

design-documents/skip-generating-product-in-category-url.md

Saving a category takes too long.
One solution is to be able to turn off automatic url rewrite generation for products on category save, so that, there is no performance issues any more when I save a category with lots of assigned products.
- for more info read the file attached to this PR

Skip generation of product in cateogries url rewrites

---

design-documents/testing/static/sniffs-consolidation.md

Proposal for PHP CodeSniffer coding standards consolidation.

Proposal: Sniffs consolidation

---

design-documents/testing/static/phpstan.md

Following types of issues can be found in Magento codebase:
- the use of undefined class;
- call to undefined function;
- missing `parent::__construct()` call;
- passed arguments mismatch, etc.
Currently such bugs cannot be detected by tools Magento uses for static checks.
[PHPStan](https://github.com/phpstan/phpstan) utilizes AST (abstract syntax tree) to perform sophisticated static code analysis which cannot be archived by using token-base approach (PHP CodeSniffer) and Reflection (PHP Mess Detector).
Add `phpstan/phpstan` to Magento `require-dev` section, update static code checks.
@buskamuza 
@paliarush 
@antonkril

Add PHPStan to Magento static checks

---

design-documents/grumphp_check.md

As a developer, you need fast feedback if you working on a pull request. 
Currently, you get feedback from  Travis after hours or days. With GrumPHP, the code can be quickly checked on every commit.
- Quik feedback for developers 
-  Better commits (fewer `fix phpcs style` commits)
Sample Config:
```yml
parameters:
bin_dir: "./vendor/bin"
git_dir: "."
hooks_dir: ~
hooks_preset: local
stop_on_failure: false
ignore_unstaged_changes: false
ascii:
succeeded: ~
failed: ~
tasks:
phpversion:
project: '7.1'
xmllint:
ignore_patterns: ["src/dev"]
yamllint:
ignore_patterns: ["src/dev"]
securitychecker:
lockfile: ./src/composer.lock
format: ~
end_point: ~
timeout: ~
run_always: false
git_blacklist:
keywords:
- "die("
- "var_dump("
- "print_r("
- "var_export("
- "exit;"
whitelist_patterns:
- …
```

Proposal: Using phpro/grumphp for local quality check

---

design-documents/asynchronous-operations/poison-pill.md

Right now our consumer depends on config/objects in-memory state. After application was bootstrapped it initialize a lot of object that are always kept in memory after first load - config, websites, etc.., since our consumers are long-living and their live time limited only by message count it leads to wrong im-memory config/objects states and we need to introduce the way to reinit them
Introduce poison pill - some message stored in Data Storage that signals that consumer must be reinited
@kandy @paliarush @vrann

MC-13864: Consumer always read config from memory

---

design-documents/class-attibute-for-referenceBlock-type-in-layout-xml.md

It is **impossible to substitute a block class** and/or customize block method(s) implementation **on a specific page keeping layout configuration of the block** (position, sorting in the layout, child blocks, arguments).
Currently available block class substitution approaches do not resolve the problem:
| Currently available approach                                                      | Why the approach does not resolve the problem  |
| --------------------------------------------------------------------------------- |:----------------------------------------------:|
| Introduce a preference for block class in di.xml                                  | Block is substituted globally, not only on the desired page |
| Remove the existing block from the layout and declare a new one …

Proposal: Allow class attribute for referenceBlock type in layout xml

---

design-documents/testing/functional/mftf-stack-configuration.md

My pull request is motivated by the fact that we should avoid monolith structure to the testing environments and should be able to keep microservices responsible for running Selenium / Selenium Hub and it's browser stack.
Currently it's impossible to build such testing stack.

Preposition for isolating Test Environment configuration

---

design-documents/module-separation.md
design-documents/module-split.md

Proposal describes different options for module names and namespaces when splitting modules.

Module separation

---

design-documents/components.md

Magento framework components are parts for `magento/framework` package, and shipped with this package. There is no way for a lightweight application to only specify components that it will use.
Also framework components do not have ability to specify magento application configuration. This leads to application framework configuration to be stored in `app/etc` and modules (mostly `di.xml`). `app/etc/di.xml` is more than 1700 lines long.
To provide the immediate solution to the 2 problems mentioned above, we need to split application framework to separate composer packages, and allow framework components to provide application configuration in `/etc` folder. This will allow to move all declarations from `app/etc/di.xml` to corresponding framework components.
1. Should there be a limitation …

Framework components as first-class citizens

---

design-documents/testing/static/coding-standard-versioning.md

The is no document that describes [Magento Coding Standard](https://github.com/magento/magento-coding-standard) versioning.
The proposal describes rules that need to be followed when making new [Magento Coding Standard](https://github.com/magento/magento-coding-standard) release.
@buskamuza 
@paliarush 
@melnikovi

Magento Coding Standard Versioning Strategy

---

design-documents/simplified-module-declaration.md

The document describes changes to module registration and management implemented in scope of "Lighter application" POC for Service Isolation project.

Simplified module declaration

---

design-documents/frontend/technical-vision.md

1. The technical vision document is a bit too long and has no table of contents.
1. I just published a scaffolding tool that this document would do well to point to.
1. Add a table of contents.
1. Add a section about scaffolding.

Add TOC, Scaffolding to tech vision doc

---

design-documents/testing/svc/improvements.md

The SVC tool has gaps in analysis for BIC-relevant changes including annotation-based type declarations, traits, visibility, and inheritance.
- **Type annotations:** Treat `@param`, `@var`, and `@return` type annotations the same as in-line declarations.
- **Traits:** Add trait analysis using `PHPSemVerChecker\Analyzer\TraitAnalyzer` as a template, treating traits the same as abstract classes.
- **Visibility:** Treat more-permissive visibility changes at the same change level as additions, less-permissive changes at the same level as removals.
- **Inheritance-related changes:**
1. Treat overriding a parent method as a changed method (PATCH) instead of an added method (MINOR).
1. Treat changing which parent interfaces, classes, or traits are implemented or extended by a class as …

Adding notes about gaps in SVC coverage to the improvements proposal

---

design-documents/Phrase_Creation_for_Improved_Translations.md

Translation is difficult and software developed in English can often neglect certain aspects of foreign languages the software might be developed in.
To best support the complexities of foreign languages, a syntax that's processable after the translation phrase is desirable.
Implementation of MessageFormatter after the translation stage of Phrase rendering, as well as the adoption of rules to ensure it can be useful to foreign languages.
* @joni-jones

Introduce MessageFormatter syntax w/ rules for usefulness

---

design-documents/node-static-content-deploy.md

[Rendered Proposal](https://github.com/magento/architecture/blob/static-content/design-documents/node-static-content-deploy.md)

Proposal to rewrite + modernize Static Content Deployment 😱

---

design-documents/frontend-html-binding.md

Developers always using HTML binding instead of mixing text/HTML binding accordingly leaves XSS vulnerabilities
Require variables/functions used for HTML binding to have 'html' syntax to indicate proper sanitization and conscious choice to use HTML binding
@melnikovi @joni-jones

Binding variables to HTML in knockout/Magento templates

---

design-documents/testing/svc/virtual-types-validation.md

According to [Versioning Policy](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/codebase-changes.html) 
we check changes for all Virtual Types in the same way as changes for API classes.
* Upgrade our [Versioning Policy](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/codebase-changes.html) 
and specify that all this is true only for Virtual types marked as API.
* Agree that non-API Virtual types are private code. According to our best practices we must not use virtual types/clases directly in the code.
* Review our codebase and remove unnecessary `````` annotations related to the Virtual types.
* Introduce a new optional attribute ```api``` for Virtual Types
Before
```xml
<virtualType name="shellBackground" type="Magento\Framework\Shell"> …
```

Validation of backward incompatible changes for Virtual Types

---

decision-making/voting-on-proposals.md

Right now there is no mechanism to handle public proposals and reflect the actual community attendance. There is a way to submit proposals and participate in the discussion, but there is no way to participate in decision-making.
Many proposals produce conflict discussion and there is no established way to resolve it. Initiators are trying to resolve this with Twitter survey, but it doesn’t show who voted and allows any Twitter user to vote.
This document represents the procedure to submit new proposals to the Magento community, vote and make decisions.
@maghamed 
@antonkril 
@okorshenko

Voting on Proposals

---

design-documents/service-isolation/integration-tests.md

What should we do with integration tests when application is deployed on separate instances?
Related issue - https://github.com/magento/service-isolation-backlog-wiki/issues/30
Preserve integration tests framework, but limit it to a single instance execution. Existing tests should be revisited and updated/removed.
@melnikovi @maghamed @paliarush

Service Isolation: Integration Tests

---

design-documents/graph-ql/framework/schema-federation.md

Apollo [schema federation](https://www.apollographql.com/docs/apollo-server/federation/introduction/) was recently released as a replacement for their [schema stitching](https://www.apollographql.com/docs/graphql-tools/schema-stitching/). The goal of this document is to evaluate the need of migration from existing Magento schema stitching mechanism to the Apollo schema federation
@akaplya

Evaluation of Apollo schema federation for GraphQL

---

design-documents/graph-ql/framework/schema-federation.md

The Apollo Federation document needed some follow-up information about setting up a gateway.
Some simple code examples are [provided in this PR](https://github.com/magento/architecture/blob/dc04b57fdb24b93985dfa2dc4f8c3cc652f2f8d0/design-documents/graph-ql/framework/schema-federation.md#apollo-gateway) to illustrate two different ways in which an Apollo Gateway server can use underlying microservices or local schemas.

Add Apollo Gateway to Schema Federation doc

---

design-documents/testing/functional/test-package.md

Not everyone understand what test types are located under `dev/tests/acceptance`
Rename `dev/tests/acceptance` to `dev/tests/ui-functional`

[MFTF] Additional improvement on test directory name

---

design-documents/webp-support.md

Speed up a page load using another image format with smaller size.
Convert and resize loaded images to the WebP format. Send the WebP image if the browser supports it.
@DrewML

Add WebP support

---

design-documents/asynchronous-operations/consumer-processes-improvements.md

The message queue consumer processes can use some improvements.
As requested by @maghamed, here's an architectural proposal based on
- https://github.com/magento/community-features/issues/180
- https://github.com/magento/community-features/issues/181
Most of this document was written from memory from what I've seen a couple of weeks ago. Therefore there can potentially be some factual mistakes in here, if that's the case, please let me know!
See the document, it provides some potential solutions.
@nuzil, @paliarush

Proposal for some consumer processes improvements

---

design-documents/graph-ql/coverage/CartPromotions.graphqls

- To provide discount descriptions with discount label and discount amount pair for all individual discounts applied both at Cart level and CartItem level. 
- Update schema to allow applying multiple coupons per cart
Cart discounts can be Applied at Different levels. 
1. Percentage of Product Price
2. Fixed amount in Product Price
3. Percentage of whole cart price
4. Buy X and get Y free
In the current implementation all the discounts applied at the cart are available as an array of labels at CartPrices.discount, without a breakdown of rule label and discount amount.
In order to reflect these price breakdown at Cart the following schema changes are proposed
```
type Cart{
// Deprecated Fields
applied_coupon: applied_coupon @deprecated(reason: "Use applied_coupons instead ")
// New field …
```

Added schema changes for cart promotions

---

design-documents/frontend/admin-guidelines.md
design-documents/frontend/technical-vision.md

There are already a handful of React applications built for Magento Admin use, but they have different dependencies and versions between them and we don't yet have a micro front-end architecture to manage them.
We must do our best to align common dependencies manually.

Introduce Magento Admin FE Guidelines

---

design-documents/graph-ql/coverage/AddProductsToCart.graphqls
design-documents/graph-ql/coverage/AddProductsToWishlist.graphqls
design-documents/graph-ql/coverage/add-items-to-cart-single-mutation.md

Right now we have 7 mutations for adding different types of products to cart. When we started working on wishlist functionality it turned out that we will have to create 14 more mutations (adding to wishlist and moving from wishlist to cart). It leads to overcomplicated flow and does not help to improve developers experience.
In order to simplify the flow it is proposed to use single mutation for all product types.
``` graphql
input CartItemInput {
sku: String!
quantity: Float
parent_sku: String, 
selected_options: [String!] # from the predefined set
entered_options: [EnteredOptionInput!] # user entered options
}
input WishlistItemInput {
sku: String
quantity: Float
parent_sku: String,
selected_options: [String!]
entered_options: [EnteredOptionInput!]
}
```
@paliarush 
@akaplya 
@maghamed …

Single mutation for adding products to cart + wishlist

---

design-documents/graph-ql/coverage/ProductPrices.graphqls

The current pricing schema has some inconsistencies and the structure is not ideal for conveying all price data (e.g. discounts).
The goal of refactoring the product pricing schema is to provide a more consistent structure for product price information.
- Type ProductInterface: existing type, with some field changes
- price: deprecated because it will be replaced by price_range
- price_range: new field, represents the min and max price of the product.
- tier_price: deprecated
- tier_prices: deprecated (use price_tiers)
- price_tiers: new field to hold tier price data. Added new field because type is different (TierPrice)
- Type ProductPrices; deprecated, replaced by PriceRange
- Type PriceRange: new type (type for ProductInterface.price_range)
- minimum_price: The minimum price of the …

Changes to Product pricing in schema

---

design-documents/graph-ql/coverage/storefront-route.md

URL routing in the PWA must handle all custom URLs maintained by the merchant, installed by extensions, and built in to Magento.
Add a `RoutableInterface` to the base schema, and require all entity types which are routable to implement it.
Add a root-level query for a client to get the entity associated with a route, along with its type and any display metadata.
@naydav 
@cpartica

add proposal for GraphQL RoutableInterface

---

design-documents/graph-ql/custom-attributes-container.md

GraphQL custom attributes containers proposal

GraphQL custom attributes container proposal

---

design-documents/graph-ql/coverage/CategoryFiltering.graphqls

Added proposal for category filtering changes in CatalogGraphQl/schema.graphqls
The current category query schema does not allow filtering with category url or name or id and  also doesn't work with multiple categories.
The goal is to add filter on the schema to return the same data with category id, category url or category name and also able to query on multiple categories
// added Category filter input.
filter: CategoryFilterInput to Query CategoryList
type Query CategoryList(
filters: CategoryFilterInput
): [CategoryTree]
input CategoryFilterInput
{
ids: FilterEqualTypeInput,
url_key: FilterEqualTypeInput,
name: FilterMatchTypeInput
} 
@paliarush 
@akaplya

Changes to Category Query in schema for filtering.

---

design-documents/graph-ql/coverage/CartAddressOperations.graphqls

1. Current GraphQl Schema for Address Operations is out-of date  with the implementation.
2. It is required to have possibility to pass 'Pickup Location Code' to the shipping address via GraphQl (see https://github.com/magento/inventory/pull/2427)
1. Actualize schema with the latest changes from Magento Codebase (first commit: 
0d1f9ef)
2. Add support of 'Pickup Location Code' field (second commit: 
9602dbb)
@paliarush

Cart operations GraphQl Schema actualization and in store pickup support

---

design-documents/graph-ql/coverage/add-items-to-cart.md
design-documents/graph-ql/coverage/shared-cart.md

Multi-device support for customer cart in GraphQL

Multi-device support for customer cart in GraphQL

---

design-documents/database/declarative-schema-database-compatibility.md
design-documents/declarative-schema-database-compatibility.md

This is a subset of #264 , covering only COLUMNS and TABLES interfaces.
Different RDBMS return Information Schema (metadata) information in different format. Magento framework should allow to switch between different implementations in order to support those different versions of DBs, as well as differences between versions.
Introduce granular interfaces, based in Information Schema standard (looking into MySQL and MariaDB definitions in this scope, links are in the document). Application can switch between different implementation based on the profile.

DB Information Schema - COLUMNS

---

design-documents/graph-ql/coverage/customer-orders.md

The current GraphQL customer orders API has limited functionality and is inconsistent with the Magento Luma theme.
Introduce changes in customer orders API with better customizability and extensibility while supporting the same set of data provided for Luma theme.
@paliarush 
@akaplya

[GraphQL] Customer Orders API

---

design-documents/graph-ql/coverage/product-compare.graphqls

GraphQL schema for product compare

Design product compare GraphQL schema

---

design-documents/graph-ql/batch-resolver.md

Current ResolverInterface does provide tools nor steer developers into creation of fast batch resolvers. By introducing new BatchResolverInterface developers will receive an array of values and arguments to resolve data for in optimal never without requiring them to mess with callbacks
and duplicated values and arguments gathering and promises management logic.
Introduce BatchResolverInterface, manage promises and create batches of values and arguments on
framework level. Deprecate existing interface
@paliarush

Graphql batch resolver

---

design-documents/graph-ql/coverage/product-reviews.graphqls

GraphQL schema for product reviews and ratings GraphQL functionality.

Product review schema with descriptions. 

---

design-documents/database/mysql-8-status-support.md

MySQL 8 added caching layer on top of table status, which is refreshed from time to time (default `86400` = `1 day`).
This leads to the behavior where returned `auto_increment` value is `null` even though it shouldn't be (there is an auto_increment column in the table).
The table status information is not calculated until the table is accessed, and (probably) the expiration time is not passed.
1. Disable MySQL cache for table status
2. Remove auto_increment from DB adapter interface

MySQL 8: auto_increment

---

design-documents/graph-ql/coverage/shared-cart.md

The current GraphQL customer cart API doesn't work across multiple devices. Also we need a way to transfer guest cart products to the customer cart once the customer logs in
We introduce one query and one mutation to achieve this functionality as described in this MD file
This proposal modifies an existing one that addressed only the first problem
@paliarush 
@akaplya 
@joni-jones

MC-21813: Unique Customer Cart retrieval on multiple devices and merge guest cart

---

design-documents/graph-ql/coverage/url-resolver-identifier.md

In reference to usage of Id in product search that became deprecated, we need an identifier to replace the ID as Int in urlResolver. This can be any unique identifier for Product, Category and CMS that can be later used to query the actual entity.
Deprecate EntityUrl.id
Add new field to EntityUrl called identifier
Return sku for EntityUrl.identifier on product, and match id for other entities
This is the Architectural proposal needed for changes
Other idea is to add filter by id back to product filter, because we did not keep backward compatibility by removing it, problem is that Id it's not part of search index right now, and we don't want it to be.

MC-22136: UrlResolver identifier

---

design-documents/graph-ql/coverage/customer-email-password-update.md

- Propose schema is inconsistent with existing one. `CustomerOutput` already exists and is used in `createCustomer (input: CustomerInput!): CustomerOutput` mutation.
``` graphql
type CustomerOutput {
customer: Customer!
}
```
- Removed `updateCustomerPassword` because `changeCustomerPassword(currentPassword: String!, newPassword: String!): Customer` already exists
@paliarush 
@melnikovi

updateCustomerV2 code style fixes

---

design-documents/graph-ql/coverage/CategoryFiltering.graphqls

Current `categoryList` query does not support pagination. Furthermore it is not possible to add pagination to this query in a backward compatible way, because the result is an array of categories with no reasonable place to put pagination information.
Introduce a new category query `categories` that will allow for filtering as well as pagination. The result object follows the schema of other queries that include filtering/pagination (e.g. `products`).
@paliarush 
@akaplya

Support pagination in category filtering

---

design-documents/graph-ql/coverage/add-items-to-cart-single-mutation.md

We do not have an explicit approach how the client can receive Selected/Eneterd options in order to add the product to cart for a single mutation
Provide details imlementation for Selected, Entered options
Propose to introduce new "uuid: String!" fields in Product Shema to solve the problem
Q/A
We cannot use "id" OR "value_id" os similar due to:
- some types already reserve theses fields, e.g BundleItemOption: (id: Int!), GiftCardProduct(value_id)

Provide option details

---

design-documents/graph-ql/coverage/company.md

We're using a _lot_ of non-null types in the Company GraphQL Schema. I don't think this is an ideal starting place.
From the GraphQL specification:
> Since Non-Null type fields cannot be null, field errors are propagated to be handled by the parent field. If the parent field may be null then it resolves to null, otherwise if it is a Non-Null type, the field error is further propagated to it’s parent field.
http://spec.graphql.org/June2018/#sec-Errors-and-Non-Nullability
In other words, a non-null type _infects_ things up the tree until it finds a non-null field.
Take the following simplified example from our company schema:
```graphql
type Query {
company: Company
}
type Company {
id: ID!
name: String!
legal_address: CompanyLegalAddress!
users: CompanyUsers
}
type CompanyLegalAddress { …
```

Remove non-nullable in many types in graph-ql/coverage/company.md

---

design-documents/graph-ql/coverage/company.md

When selecting from `CompanyRole.permissions`, you get a `[String]` of permission IDs. A UI may wish to capture the permission's label text in the same request.
Change permissions to point to the appropriate type (`CompanyAclResource`)
@kokoc 
@paliarush

Change CompanyRole.permissions from [String] to [CompanyAclResource]

---

design-documents/graph-ql/coverage/company.md

1. In `Company.id`, the `id` parameter has been changed to be non-nullable. This query only needs to do one thing well: lookup a company-associated user by ID. The schema already exposes a way to obtain the currently logged in `Customer` in other places.
2. Updated the descriptions of the root `Query` types to be a bit less verbose
3. Removed non-nullability from the "Check" types' response fields. If we add any other fields to those types later, the current field encountering an error would propagate up and infect the whole type. Can always make it non-nullable later without a breaking change

GraphQL B2B Company schema updates

---

design-documents/cache/jmeter-test/clean-cache-test.jmx
design-documents/cache/non-blocking-stale-cache.md

Currently, we have two cache types(Block and Config) that uses lock mechanism to avoid parallel cache generation and excessive resource utilization. 
So every time we want to generate and write a new cache, we acquire a lock and parallel process wait until lock released. 
When the lock is released, customer get fresh data from storage.
We usually think that trade-off with lock waiting is acceptable from the performance side. 
But the larger amount of Blocks or Cache merchant has, the more time he will wait in locks. 
In some scenarios, we could wait  **numbers of keys** * **lookup timeout**  amount of time in parallel process. 
We noticed that in some rare cases merchant can have hundreds keys in Block/Config cache, so even small lookup timeout for lock may cost seconds.
Was proposed by …

Non blocking cache writing mechanism

---

design-documents/graph-ql/coverage/SubscribeEmailToNewsletter.graphqls

There is a subscribe field on a standard Magento storefront:
Currently, GraphQl does not have a mutation which allow to subscribe guest/customer into a newsletter subscription.
```
type Mutation {
subscribeEmailToNewsletter(email: String!): SubscribeOutput @doc(description:"Adds an email into a newsletter subscription")
}
type SubscribeOutput {
status: Int! @doc(description: "Returns a status of subscription")
}
```
`SubscribeOutput`.`status` may return the next statuses:
- [1 - Subscribed](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Newsletter/Model/Subscriber.php#L56)
- [2 - Not Active](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Newsletter/Model/Subscriber.php#L57)
Depends on status the possible messages will be displayed, for example …

magento/architecture#: GraphQl. Add a mutation for subscribe feature

---

design-documents/graph-ql/coverage/requisitionList.graphql
design-documents/graph-ql/coverage/requisitionList.graphqls

Coverage for B2B Requisition List
Schema  for B2B Requisition List 
Queries
- All requisition list are available under customer query
- A single requisition list can be queried by Id
- Export Requisition List
Mutations
- Create Requisition List
- Rename Requisition List
- Add Items
- Remove Items
- Update Items
- Copy Items to cart
- Copy Items to another list
- Move Items to another list
@paliarush 
@lenaorobei

b2b requisition list schema

---

design-documents/graph-ql/coverage/customer-orders.md

1. SalesItemInterface is not being used properly as an interface
2. Unclear how to return parent and child items in Orders/Invoices for bundle and configurable products
3. Some shipment fields did not align with available data
1. Remove SalesItemInterface and instead use unique types for each item type (OrderItem, InvoiceItem, etc) that have only relevant fields and an ID link to the associated order item
2. For items that distinguish parent and child items (e.g. OrderItem and InvoiceItem) for complex products we introduce an item interface (e.g. OrderItemInterface) so that complex product types can add fields (e.g. BundleOrderItem)
3. Remove ShipmentTracking.link; change ShipmentTracking.method to ShipmentTracking.title because available data does not align with shipping method
Other …

Customer order schema updates

---

design-documents/graph-ql/coverage/Cart.graphqls

When querying cart_items on a cart, the parent product is returned for configurable cart items. This is because ConfigurableCartItem.product corresponds to the parent product. In some cases it is desired to have the configured child product.
One use case is that the product's image is the parent product's image, so it doesn't match the configured selection.
The proposed solution is to add an additional field to ConfigurableCartItem, that will contain the simple product that is the configured variant.
@paliarush 
@akaplya

Add configured_variant to ConfigurableCartItem

---

design-documents/graph-ql/coverage/reward-points.graphqls

Reward point exchange rates are discrete (not continuous) so a float value representing the exchange rate it not sufficient.
i.e.
An earning rate of $10:100points does not mean that $1 will earn 10points, so an exchange rate of 10% is misleading.
The customer gets 100points for every $10 spent, not 10 points for every $1 spent.
Redemption follows the same principle.
Create a type for exchange rates that explicitly states the point:money conversion.
@paliarush 
@DrewML

[Reward Points] Add RewardPointsRate type for RewardPointsExchangeRates

---

design-documents/graph-ql/id-fields-object-types.md

[Rendered Document](/magento/architecture/blob/id-fields/design-documents/graph-ql/id-fields-object-types.md)

Add document with suggestions for ID fields

---

design-documents/graph-ql/coverage/Wishlist.graphqls

Based on issue discovered in https://github.com/magento/partners-magento2ee/pull/248.
There is a [separate PR](https://github.com/magento/magento2/pull/29148) with some of the work.
Proposal was approved by @nrkapoor and @fnhipster, but sending through the proper channels for review.
- [Comment summarizing the problem this PR attempts to solve](https://github.com/magento/partners-magento2ee/pull/248#issuecomment-649749589)
- [Comment where revised solution is presented](https://github.com/magento/partners-magento2ee/pull/248#issuecomment-650314163)

Wishlist updates proposed in Magento 2 Commerce PR (internal)

---

design-documents/graph-ql/coverage/add-items-to-cart-single-mutation.md

**This (if approved) impacts an in-flight PR**: https://github.com/magento/magento2/pull/28210
These changes are based on discussions I've had with @prabhuram93 and @nrkapoor.
There were a few concerns I wanted to address:
1. We should be using the `ID` type for IDs, because we don't want clients using them for anything but lookups. [Mentioned in a separate design document](https://github.com/magento/architecture/pull/395)
2. The document mentioned that `id_v2` was a temporary field until we start using UUIDs. If we use the `ID` type, though, we shouldn't need a temporary field. If a client deploys a new version of the GraphQL API (after we switch from base64 >> uuid) and a client has cache entries for the old IDs, those old entries just won't be looked up in the client-side cache …

Propose renaming id_v2 to something more permanent, and change type

---

design-documents/graph-ql/coverage/gift-card.md

1. For a gift card, 6 entered options are possible. Sender name/email, Recipient name/email, Message, Custom gift card amount.
Not all fields are needed/required for the clients to fill in. This options metadata should be made available to the clients when adding a giftcard product to cart.
2. When clients send this data they need a uid to distinguish each option and uid is not supposed to be generated on the client side. So when we pass in the options metadata a server generated uid should be made available to the clients.
Add an additional field gift_card_option under GiftCardProduct which can provide this metadata.

Proposal for Gift Card Options

---

design-documents/graph-ql/coverage/Wishlist.graphqls

1. The current schema proposed for Wishlist has conflicts with existing Wishlist.items
2. Changes from https://github.com/magento/architecture/pull/395 needs to be propagated to this new schema.
3. Typo on GiftCardWishlistItem.
1. Deprecate existing Wishlist.items and introduce Wishlist.items_v2
2. Changed Id fields from String to ID
3. Updated fields on GiftCardWishlistItem
@paliarush @DrewML @nrkapoor

Proposed changes for Wishlist schema modifications

---

design-documents/graph-ql/coverage/company.md

The schema for the [B2B Company Structure](https://docs.magento.com/m2/b2b/user_guide/customers/account-company-structure.html) has a few problems in my opinion:
1. `isEditable` seems out of place. There are other APIs in this company schema that a UI can use to determine if a user has permissions to edit the company structure.
2. The description of the `CompanyHierarchyElement.type` field is `Hierarchy element type: 'customer' or a 'team'`, but is typed as a `String`, meaning the client-side and server-side have implicit shared constants not defined in the schema
3. `CompanyHierarchyElement` does not provide any edges for a query to get access to the `Customer` or `CompanyTeam`. Instead, it decides what the UI has to show via a `text` and `description` field. If more info about the …

Refactor B2B Company Structure query to remove recursive type and add more edges

---

design-documents/graph-ql/coverage/Swatches.graphqls

Proposed schema for adding swatch data for configurable options.
``` graphql
{
products(filter: {sku: {eq: "configurable-product"}}) {
items {
... on ConfigurableProduct{    
configurable_options{
values {
label
swatch_data{
value
}
} 
}
}
}
}
}
```
- This approach does not align with [current implementation of product swatches](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/SwatchesGraphQl/etc/schema.graphqls), but is semantically correct.
- Current implementation of product swatches cannot be changed in order to use `SwatchDataInterface` due to BC.
@akaplya 
@paliarush

magento/graphql-ce#196: Swatches: expose Hex color code and swatch images

---

design-documents/storefront/Readme.md
design-documents/storefront/configuraiton-propagation.md

Existing Magento monolith is responsible for the whole cycle of data and user workflow.
Magento Admin Panel contains configuration settings for all areas of the application, including Admin Panel behavior, storefront UI, etc.
With Storefront being a separate service (or set of services), should configuration settings in Magento Admin Panel be propagated to storefront service?
If yes, in what way?
Task: https://github.com/magento/catalog-storefront/issues/154
Each case will be different and will require dedicated attention.
Provided are guidelines on how to make a decision in each such case.

Admin Panel Configuration propagation to Storefront

---

design-documents/graph-ql/coverage/negotiableQuotes.graphqls

This PR builds on the great work done by @G-Arvind in #381.
Notes:
- Few TODOs left in here, but the majority of things are complete and ready to review
- I've tried to leave thorough notes wherever things seemed ambiguous for a dev that implementing this
- This does not cover Negotiable Quote checkout, which will be covered in a separate story
- Some payment and shipping types have been removed from the original design, because B2B doesn't deal with payment types until checkout process (see previous note). They'll be added back in the Negotiable Quote checkout story
- We don't have REST API coverage for the "History" feature of negotiable quotes, so I had to read the UI code and work backwards. Would appreciate extra scrutiny of those types
For reviewers, here's some resources that …

Iterating on Negotiable Quote GraphQL schema design

---

design-documents/graph-ql/coverage/requisitionList.graphqls

Requisition List Items size can be huge and can be a performance issue. Current schema doesn't  handle it.
Update Requisition List items cannot handle edit config variation, adding the support from Alex request
Adding pagination to Requisition List Items
Update to Req list items Input for supporting custom options, configurable options.
@nrkapoor 
@DrewML 
@paliarush 
@cpartica

req list items pagiantion

---

design-documents/graph-ql/coverage/AddProductsToCart.graphqls

Based on the uid changes, new/existing mutations in the future will be leveraging the EnteredOptionInput type. 
```
input EnteredOptionInput {
uid: ID!
value: String!
}
```
Based on this architecture [AddProductsToCart](https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/AddProductsToCart.graphqls) the type EnteredOptionInput is inferred to be in QuoteGQL module. 
The same type is being used in WishlistGQL [Wishlist](https://github.com/magento/architecture/blob/0cc6ac2eba3177b23409cb230e45ba394c949914/design-documents/graph-ql/coverage/Wishlist.graphqls#L29) for its mutations. This creates a dependency between WishlistGQL and QuoteGQL.
There a couple of ways to fix this.
Solution 1. Move the ```EnteredOptionInput``` to the GraphQL framework module, which …

Proposal to solve dependency in GQL schema between QuoteGQL and WishlistGQL

---

design-documents/graph-ql/coverage/requisitionList.graphqls

Whenever we add requisition list items to cart if the cart has items we have an option to replace or merge the requisition list items with the existing cart items. We don't have the option in the addRequisitionListItemToCart mutation.
Added a seperate parameter ( is_replace ) to the addRequisitionListItemToCart mutation.
@nrkapoor @paliarush

Added replace or merge option for addRequisitionListItemToCart mutation

---

design-documents/graph-ql/coverage/negotiableQuotes.graphqls

The NegotiableQuote Graphql architectural schema was not aligned with the implementation. Need to change the type to implementation fit.
During the Development time of the Negotiable Quote GraphQl, We have faced ENUMERATION TYPE Null Issue for the NegotiableQuoteHistoryStatusChange with old_status because old_status will be return null for the first iteration of history log of the current Quote and this will throw the error. We have added String type instead of ENUM.
Update schema to reflect the implementation of items object and NegotiableQuoteHistoryStatusChange.
@paliarush 
@DrewML

negotiable-quote-graphql-schema-improvement

---

design-documents/graph-ql/mutation-error-design.md

[Rendered Document](/magento/architecture/blob/mutation-error-design/design-documents/graph-ql/mutation-error-design.md)
cc @fnhipster @sirugh who I've had recent discussions with re: error discoverability for headless UI
Some related blog posts and ideas:
- https://artsy.github.io/blog/2018/10/19/where-art-thou-my-error/
- https://blog.logrocket.com/handling-graphql-errors-like-a-champ-with-unions-and-interfaces/
- https://graphqlme.com/2018/02/24/handling-errors-in-graphql/

Add document with suggested guidelines around mutation error design

---

design-documents/graph-ql/coverage/b2b/negotiableQuotes.graphqls

Rename id fields in negotiableQuotes.graphqls

---

design-documents/graph-ql/coverage/b2b/requisitionList.graphqls

Rename id fields to uid in requisitionList.graphqls

---

design-documents/graph-ql/coverage/returns.graphqls

Rename id fields to uid in returns.graphqls

---

design-documents/graph-ql/coverage/catalog/remove-product-attributes.md

At the moment, Magento exposes Product Interface as an interface with the dynamic structure. As a result, the Product Interface in Magento has a state. This creates unnecessary complexity on the GraphQL tier. (it is challenging to cache, read schema, aggregate stores behind the same gateway so on).
Remove the state from the interface.

[GraphQL] Remove dynamic attributes from ProductInterface

---

design-documents/graph-ql/coverage/catalog/compare-list.graphqls

Rename all the id fields to uid in compare-list.graphqls
@prabhuram93 @DrewML @melnikovi

Rename all the id fields to uid in compare-list.graphqls

---

design-documents/graph-ql/coverage/cart/Cart.graphqls

@melnikovi @prabhuram93 @DrewML

Rename all id fields to uid in cart.graphqls

---

design-documents/graph-ql/coverage/deprecate-createEmptyCart-add-createGuestCart.md

[Rendered Proposal](/magento/architecture/blob/deprecate-createEmptyCart-add-createCart/design-documents/graph-ql/coverage/deprecate-createEmptyCart-add-createGuestCart.md)

Proposal: Deprecate `Mutation.createEmptyCart`, add `Mutation.createGuestCart`

---

design-documents/graph-ql/coverage/cart/Cart.graphqls
design-documents/graph-ql/coverage/customer-address-pagination-change.graphqls
design-documents/graph-ql/coverage/customer/Wishlist.graphqls
design-documents/graph-ql/coverage/customer/customer-orders.md

Current Graphql endpoints like cartItems, address, order  items etc are not paginated. In B2B scenarios, these could impact performance because of large number of items will be returned in collection.
Adding pagination for  entities.
Cart Items,
Order Items,
Customer Addresses 
@nrkapoor 
@paliarush 
@DrewML

pagination to support entities in b2b

---

design-documents/graph-ql/coverage/customer/gift-registry.graphqls

When creating gift registry, adding gift registrants are mandatory.
Add an input field to support adding gift registrants
@melnikovi @cpartica @nrkapoor

Enabling adding gift registrants while creating gift registry

---

design-documents/graph-ql/coverage/dynamic-blocks.graphqls
design-documents/graph-ql/coverage/dynamic-blocks.md

Allow to get content of dynamic blocks in PWA.
@cpartica, @prabhuram93

GraphQL schema for dynamic blocks

---

design-documents/graph-ql/coverage/b2b/company.md

Fix naming conventions and optional/required fields.

Fix naming conventions and optional/required fields

---

design-documents/graph-ql/coverage/b2b/requisitionList.graphqls

Align requisition list schema with best practices.
@cpartica, @prabhuram93

Fix naming conventions and optional/required fields in requisition list GraphQL schema

---

design-documents/graph-ql/coverage/b2b/company-credit.md

Add missing uids to the types and validate optional/required fields.
@cpartica, @prabhuram93

Fix naming conventions and optional/required fields in company credit GraphQL schema

---

design-documents/graph-ql/coverage/b2b/requisitionList.graphqls

Schema changes to align uid naming and CRUD naming for Requisition lists.
Matching names with wishlist https://github.com/magento/architecture/pull/442
Schema changes are added.

Requisition list: align schema with uids and delete confirmation naming conventions

---

design-documents/graph-ql/coverage/search.md

This PR contains graphql schema changes required to introduce new search functionality such as 
* highlights - parts of product attribute values which contain matched words. The words might be slightly different compared to the input, so they can't be calculated on the client side.
* multi-facets - possibility to check multiple values per facet. This means that in addition to filtered results we need to get the facets without any filters. 
* advanced range facets (prices) - support of slider UX element. Basically, we need to extract additional information about price ranges, like min value; max value, etc.
* suggestions, "did you mean?", etc  - not a part of the proposed schema, but we need to make sure these parts are fit well in the future.
* preselected variations - most relevant …

ECP-469: Finalize new search schema

---

design-documents/graph-ql/coverage/customer/gift-registry.graphqls

The current schema doesn't follow the default Magento behavior on GiftRegistry updating.
We shouldn't have the possibility to update the registry's type.
@prabhuram93 @cpartica @nrkapoor

We shouldn't give the possibility to update the registry's type.

---

design-documents/graph-ql/coverage/customer/reward-points.graphqls

Customer Reward Points UID Changes in the schema file.
To keep consistency throughout the GraphQL schema, we have replaced the Id field with Uid.

Reward points Uid changes

---

design-documents/graph-ql/coverage/mergeCarts-optional-destination.md

[Rendered Proposal](/magento/architecture/blob/mergeCarts-optional-destination/design-documents/graph-ql/coverage/mergeCarts-optional-destination.md)
There are no breaking changes and no deprecations.

Make destination param nullable in mergeCarts

---

design-documents/graph-ql/coverage/quote.graphqls

Applicable FPT doesn't show in GraphQL on cart Item prices after an address has been set.
STEPS TO REPLICATE:
Enable FixedProductTax following documentation https://docs.magento.com/user-guide/tax/fixed-product-tax-configuration.html
Create product FPT attribute
Assign it to appropriate Attribute sets
Create test product having FPT sku and FPT attribute created before as property
Assign FPT to Texas or another state on the FPT property related to US country
Create cart by GraphQL
Set Shipping Address to cart by GraphQL
Add the product to cart by GraphQL
Query the cart by GraphQL
ACTUAL RESULTS
"fixed_product_taxes" empty in the response, screenshot attached
We need a field on cart Item prices and not on Product Interface which shows all FPTs for all states which is not very helpful.

PWA-1486: Define the schema for FPT cart item prices

---

design-documents/graph-ql/coverage/b2b/negotiableQuotes.graphqls

The current storeConfig query does not contain information about the Negotiable Quote configuration.
Extend the storeConfig query from within the NegotiableQuoteGraphQl schema to include this.
@cpartica 
@prabhuram93

PWA-1631: Add the Negotiable Quote admin configuration information to the storeConfig query

---

design-documents/graph-ql/coverage/b2b/negotiableQuotes.graphqls

Mutations in schema is not align with statuses on operations that might have partial or total success, which is an overall effort. 
We also can't sort the quotes returned. 
To align mutations schema with operations that might have partial or total success, we need to add statuses.
Also we can add sorting on quotes solving the sorting problems

Adjust neg. quote operations to contain sort and status

---

design-documents/graph-ql/coverage/b2b/negotiableQuotes.graphqls

We want to report the non-negotiated price of a negotiable quote
Internal ticket: [PWA-1663](https://jira.corp.magento.com/browse/PWA-1663)
* Add a field to the CartPrices type originally in QuoteGraphQL with the original_total_price value from the negotiable_quote table
* Add a field to the CartItemPrices type originally in QuoteGraphQL with the original_price value from the negotiable_quote_item table
* Add original_row_total and original_row_total_including_tax fields to the CartItemPrices type originally in QuoteGraphQL with calculated values based on the original_price and original_tax_amount values from the negotiable_quote_item table multiplied by item quantity
@cpartica @prabhuram93

Add original_total_price to prices field on negotiable quotes

---

design-documents/graph-ql/coverage/b2b/negotiableQuotes.graphqls

A user should not be able to add a comment to a Negotiable Quote without submitting it for review.
Removed the mutation from the schema.

Remove addNegotiableQuoteComment mutation

---

design-documents/graph-ql/coverage/b2b/negotiableQuotes.graphqls

Negotiable Quote GQL implementation restricts sorting via multiple fields. This PR enables schema to enforce that restriction.
Added changes in teh schema
@cpartica  @pdohogne-magento

Enforce restriction on multiple sorting through Negotiable Quote schema

---

design-documents/graph-ql/coverage/b2b/negotiableQuotes.graphqls
design-documents/graph-ql/coverage/quote.graphqls

Negotiable quote needs additional initial vs resulting prices on both item and total level
We don't have an elegant way to do this unless we add those to the CartPrices and CartItemPrices objects, which for cart they're not relevant.
Add interfaces to solve this problem. Cart contains most of the Neg. Quote price fields
@pdohogne-magento

modify schema to fit negotiable quote needs

---

design-documents/graph-ql/coverage/customer/gift-registry.graphqls
design-documents/graph-ql/directives.graphqls

Luma has this operation to add all items from cart to gift registry. We don't have this in graphql.
Not only that we don't have it yet, but we have opened a lot of use cases by adding individual items to gift-registry, which we don't want to support just yet.
Add specialized query to move items to cart to gift registry. Alternatively we could use this query to empty the cart while doing so or not.

[GQL gift registry] cart management mutations

---

design-documents/graph-ql/improved-caching.md

Vary header exposes the wrong data in GraphQL and poses a problem with dish cache in browser.
We also need to add private data part of the cache key like Customer-Group 
Fix the Vary header output in GraphQL
Add `X-Magento-Request-Id` on output as a replacement for X-Magento-Vary cookie and fix VCL

X vary cache proposal

---

design-documents/graph-ql/coverage/catalog.graphqls

* [MC-42795](https://jira.corp.magento.com/browse/MC-42795) GraphQl products query layered navigation filters return incorrect child categories list

MC-42795: GraphQl products query layered navigation filters return incorrect child categories list

---

design-documents/graph-ql/coverage/b2b/negotiableQuotes.graphqls

We cannot currently support end-to-end checkout of negotiable quotes in GraphQL because several mutations are missing, including one to set the payment method on the negotiable quote. (Other missing mutations will be addressed separately.)
Add the setNegotiableQuotePaymentMethod mutation to the NegotiableQuoteGraphQl schema and return the full negotiable quote as the output.

PWA-2114: Create mutation to set payment method on negotiable quote

---

design-documents/graph-ql/coverage/b2b/negotiableQuotes.graphqls

In our GraphQL schemas, the NegotiableQuote type does not contain the same information as the Cart type. We need to identify the missing fields so that we can make the NegotiableQuote schema definition consistent with Cart.
update the NegotiableQuote type schema definition to be consistent with the Cart type

PWA-2150: [Spike] Identify discrepancies between GraphQL types Cart and Negotiable Quote

---

design-documents/graph-ql/coverage/re-captcha.graphqls

Would like to support reCAPTCHA v3 Invisible on PWA storefronts.
Add reCAPTCHA configuration to `storeConfig` response in our core extension, magento-commerce/magento2-pwa.

[PWA-2062] reCAPTCHA for PWA

---

design-documents/graph-ql/coverage/b2b/negotiableQuotes.graphqls
design-documents/graph-ql/directives.graphqls
design-documents/graph-ql/result-status.graphqls

PWA-1611: Adding the ability to report partial successes on batch operations in Negotiable Quote
Some batch mutations in the Negotiable Quote module can have partial successes where some of the items succeed and some fail.  This needs to be reported in a usable way.
Add a tri-state result status field to these operations with a `SUCCESS`, `FAILURE`, and `PARTIAL_SUCCESS` enum, and include an array result field that reports either a success or a typed failure for each item specified in the batch.

PWA-1611: Adding the ability to report partial successes
