proposals/mftf-package.md

Initial proposal of MFTF packaging

Magento Functional Testing Framework packaging

---

design-documents/add-redeem-method.md

Redeem functionality is missing from the gift card API

Add redeem method to the Gift card API

---

proposals/deprecate-js-component-mixins.md

Originally from https://github.com/magento/magento2/issues/17842

Add proposal to deprecate JS Component mixins

---

design-documents/asynchronous-import/asycnhronous-import-service.md
design-documents/asynchronous-import/base-extension.md
design-documents/asynchronous-import/import-ui.md
design-documents/asynchronous-import/postman/Asynchronous Import Module.postman_collection.json
design-documents/asynchronous-import/retry-and-profiling.md

This PR is showing idea and basic of Asynchronous import module.
Proposal is splitted on 3 phases. 
- Mail module implementation
- UI
- Advanced features

Asynchronous import module

---

design-documents/asynchronous-import/base-extension.md

After several discussion we change input body of Import Source call and also changed Endpoint

Change schema of Import sources to AsyncImport module

---

design-documents/frontend/technical-vision.md

The JavaScript ecosystem can be daunting when presented with so many options. Which libraries do you choose and why this one over that one?
<a href="https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f"><img src="https://cdn-images-1.medium.com/max/1600/1*raWO3dhM4jMjf9VY-kZzNg.png" alt="so many JavaScript options"></a>
This document is intended to set you off on the right foot. Think of it as a generic guide for new front-end applications. Your specific project will most likely have needs of its own that deviate from this guide. That's totally fine and expected.

Add front-end tech vision doc

---

.github/PULL_REQUEST_TEMPLATE/design-document.md
design-documents/README.md

Resolves https://github.com/magento/architecture/issues/2

Templates for Design Document and corresponding PR

---

design-documents/asynchronous-import/base-extension.md
design-documents/asynchronous-import/retry-and-profiling.md

I updated 3rd phase of Async import to use UUID for operations

Update endpoints with UUID usage for profiling

---

design-documents/frontend/prettier.md

[Rendered](https://github.com/magento/architecture/blob/prettier/design-documents/frontend/prettier.md)

Replace JSCS + Stylistic ESLint rules with Prettier

---

design-documents/service-isolation.md
design-documents/services-decomposition-guidelines.md

- working with data
- deployment of services

Update service decomposition guidelines

---

design-documents/cookies.md

Extend https://docs.magento.com/m2/ce/user_guide/stores/cookie-reference.html with reference of cookies to specific features where they are used.

Cookies relation with modules

---

design-documents/admin-controller-extending.md

Extending backend controllers in frontend controllers may lead to unexpected behavior
Create a PHPStan rule to prevent this
@buskamuza

Document regarding controllers extending each other

---

.github/pull_request_template.md

Fix "Component Assignments" link

---

README.md

Fix "affected components" link

---

design-documents/testing/functional/versioning-and-backward-compatibility-policy.md

https://github.com/magento/architecture/issues/103

Update Magento MFTF Tests Versioning and Backward compatibility Policy with modifying argument type for ActionGroup

---

design-documents/cookies.md

Added more information about cookies.

Updated Cookies Information

---

design-documents/distributed-deployment-configuration.md

Configuration for enabling distributed deployment

---

design-documents/testing/coding-standards/improvements.md
design-documents/testing/svc/improvements.md

Our backward compatibility tools are not perfect and we need to:
- Eliminate false positive failures
- Improve coverage
@buskamuza @fascinosum @lenaorobei 
Mentioning specific reviewers you raise their attention, increase chances of getting valuable input, speed up the review process, and so put the ground to a successful and valuable design document.

Static testing improvements

---

design-documents/testing/static/coding-standard-versioning.md

Included cadence, side effects, and notifications updates discussed today
We still had some unknowns regarding cadence and release notes.
Monthly release cadence, no breaking changes, changes in priorities and scoring synchronized with M2 patch releases, changes in test set and fail conditions synchronized with M2 minor releases.
@lenaorobei @antonkril

Updated Coding Standard release proposal

---

design-documents/service-isolation.md
design-documents/service-isolation/implementation.md

- Vision separated from Implementation
- The current state grouped
- The desired state grouped
- explanation about BFFs and Domain Services added to the desired state
- Design principles grouped
- Additional requirement grouped

Vision and Implementation separation

---

design-documents/mail-library-improvements.md

Mail library improvements

---

design-documents/testing/functional/versioning-and-backward-compatibility-policy.md

* MFTF BIC policy needed a comprehensive list of `change => version requirement`
* I added a version increase matrix to the BIC policy page, containing all the permutations of MFTF test changes
@okolesnyk

 Update MFTF Versioning and BIC page

---

design-documents/graph-ql/framework/subscriptions.md

Evaluate potential benefits and drawbacks due to implementation of GraphQL subscriptions framework.
@akaplya

GraphQL subscriptions evaluation

---

design-documents/js-backward-compatibility-checking.md

Create an automated script that checks for backward incompatibility in the same manner for PHP Classes and Interfaces.
Utilizing Acorn to statically analyze the different JS file versions and adding the response to the report generated by SVC module.
@DrewML

[HLD] JS backward compatibility checking

---

design-documents/testing/functional/bdd-like-mftf-output.md

Increase business value from Magento Functional Testing Framework output
* User-defined labels
* Auto-generate labels
@okolesnyk

MFTF: Friendly labels to elements, actions and action groups

---

design-documents/graph-ql/versioning.md

GraphQL versioning proposal.
@buskamuza 
@maghamed 
@mslabko

GraphQL versioning proposal

---

design-documents/batch-query-services.md

Batch query services. This document specifies how input/output arguments should look like to implement batch query services

Batch query services

---

design-documents/graph-ql/lightweight-resolver.md

Fixed grammar mistakes. 
'File needs correction or should be rewritten.'

Grammar and typo fixes

---

design-documents/testing/coding-standards/phpcompatibility.md

Add PHPCompatibility to code style ruleset.

PHPCompatibility

---

design-documents/abstract-method-removal.md

The`AbsractMethod` removal strategy proposal.

Added the proposal for Abstract Method removal

---

design-documents/graph-ql/coverage/store-pickup.graphqls

Schema for store pickup GraphQL API.
GraphQL schema proposed in this PR is approved by PO (@mbrinton01) and current proposal should replace https://github.com/magento/architecture/pull/275 if approved.

Schema for store pickup GraphQL API

---

design-documents/graph-ql/storefront-api.md

Typo fixes

---

design-documents/Investigation-on-removal-of-dependency-on-Auto_Increment-Id-in-application.md

When trying to upgrade Magento to MySQL v8 we noticed that `AUTO_INCREMENT` is being relied on in different places. Since no decision could be taken directly, we were asked to investigate and report on this subject.
No solution is provided by this PR, just a document that can help taking the decision.
@buskamuza

MC-19826: Adds investigation on removal of dependency on Auto_Increment

---

design-documents/async-image-resize.md

Full image resize triggered by catalog:image:resize command may take dozen of hours
Proposed way to speed up such process - implement asynchronous image resizing 
with possibility to run several workers in parallel mode
@buskamuza

Asynchronous image resizing proposal

---

design-documents/graph-ql/framework/attributes-metadata-in-graphql-schema.md
design-documents/graph-ql/framework/attributes-metadata.md

GraphQL Directives for EAV attribute metadata

GraphQL Directives for EAV attribute metadata

---

design-documents/graph-ql/coverage/customer-email-password-update.md

GraphQL schema for updating customer email and password.

GraphQL schema for updating customer email and password.

---

design-documents/message-queue/PHPEnqueueLibrary.md

Integrate feedback from Lyzun on Handlers

---

design-documents/graph-ql/storefront-api.md

Updated Storefront API request format according to the latest implementation changes.

Update Storefront API request format

---

design-documents/graph-ql/coverage/customer-orders.md

Added ID field to order, invoice, credit memo, shipment entities

 Added ID fields to sales entities

---

design-documents/graph-ql/coverage/customer-orders.md

Updated Customer Orders GraphQL schema to make it compatible with B2B

Extended Customers Orders GraphQL schema

---

design-documents/graph-ql/coverage/customer-orders.md

GraphQL Customer Orders

---

design-documents/graph-ql/coverage/customer-reorder.graphqls
design-documents/graph-ql/coverage/gift-wrapping.md

GraphQL Schema for Gift Wrapping and Gift Message

GraphQL Schema for Gift Wrapping and Gift Message

---

design-documents/graph-ql/coverage/customer-password-reset.md

GraphQL schema for customer password reset functionality

GraphQL schema for customer password reset functionality

---

design-documents/graph-ql/coverage/customer-orders.md

- Added tax details 
- Added shipping&handling details
- Added customer's chosen delivery method to order details

Update order total amounts details

---

design-documents/graph-ql/coverage/payflowpro-vault.md

- Extended input types to support Vault for PayPal Payflow Pro

ECP-425: Customer Stored Payments schema

---

design-documents/graph-ql/coverage/reward-points.graphqls
design-documents/graph-ql/coverage/reward-points.md

https://jira.corp.magento.com/browse/ECP-756

ECP-756: GraphQL Schema for Rewards

---

design-documents/graph-ql/nullability.md

[Rendered Document](/magento/architecture/blob/nullability/design-documents/graph-ql/nullability.md)
Prior discussions about nullability:
- https://github.com/magento/architecture/pull/372
- https://github.com/magento/architecture/pull/381#discussion_r431408317
- https://github.com/magento/architecture/pull/368#discussion_r414907353

Added design document with nullability recommendations for GraphQL schemas

---

design-documents/graph-ql/coverage/negotiableQuotes.graphqls

Coverage for B2B Negotiable quotes
Schema for B2B Requisition List
Queries
- Get single NegotiableQuote
- Get All NegotiableQuotes
- Estimate shipping cost for NegotiableQuote
- Estimate Shipping Cost by AddressId for NegotiableQuote
- estimate Shipping information for NegotiableQuote
Mutations
- Update Price
- Request a NegotiableQuote
- Set shipping method to NegotiableQuote

B2B NegotiableQuote GraphQL Schema

---

design-documents/graph-ql/coverage/company.md

Some behavior was unclear, so I added notes to guide the implementation.
Some return types seemed incorrect, so I changed them to something that makes more sense
@kokoc 
@DrewML

Company schema changes to describe behavior and fix some return types

---

design-documents/graph-ql/coverage/AddProductsToCart.graphqls

1. Changes need to be propagated from these 2 PRs https://github.com/magento/architecture/pull/396, https://github.com/magento/architecture/pull/395
1. Update id field types from String! to ID!
2. If a new mutation is expected to use encoded ids, then name it ```uid```
@paliarush @DrewML

Propose changes to field types in Add Products to cart mutations

---

design-documents/graph-ql/id-improvement-plan.md

[Rendered Document](https://github.com/magento/architecture/blob/MC-36347-design-doc/design-documents/graph-ql/id-improvement-plan.md)

MC-36347: ID Improvement Plan

---

design-documents/graph-ql/id-fields-object-types.md

Reference: #415 
@melnikovi 
@nrkapoor

Update GraphQL Object ID Guidance document to use new "uid"

---

design-documents/graph-ql/coverage/returns.graphqls
design-documents/graph-ql/coverage/returns.md

Working with ticket https://github.com/magento/magento2/issues/29479 I see that in RMA module we have additional fields in the request (order_id, customer_custom_email)

magento2/issues/29479 Returns : graphql implementation

---

design-documents/graph-ql/naming-conventions.md

Just documenting the conventions that are already being followed, so we have something to link to.

Document existing GraphQL naming conventions

---

design-documents/testing/functional/versioning-and-backward-compatibility-policy.md

MFTF SVC policy doc update
- [MQE-2247](https://jira.corp.magento.com/browse/MQE-2247)

MQE-2247: Implement additional <section> and <operation> entity use cases in SVC tool

---

design-documents/graph-ql/coverage/b2b/negotiableQuotes.graphqls

Negotiable Quote With UID and label changes for the schema.graphql file.
FYI @nrkapoor

uid and label changes

---

design-documents/graph-ql/coverage/catalog/configurable-options-selection.graphqls

The schema structure of the existing proposal has some drawbacks, which need to be updated.
Please refer to the schema file for the proposed schema.
Outstanding Questions
1. Is sort_order needed?
2. is thumbnail needed?
@melnikovi @cpartica

Updates to Configurable Options schema

---

design-documents/graph-ql/coverage/customer/Wishlist.graphqls

Schema additions for Multiple Wishlist and reflecting back minor changes from code reviews.
- Schema changes are added.
- Store config changes needed for wishlist are added
@melnikovi @cpartica

Schema additions for Multiple Wishlist and Patching back minor updates from code reviews

---

design-documents/abstract-method-removal.md

Correction of typo - AbsractMethod

Correction - AbsractMethod to AbstractMethod

---

design-documents/storefront/catalog/product-options-and-variants.md

This document proposes to review options and variants management approach to :
* achieve more consistent behaviors across the options.
* reduces data duplication caused by the existing variants matrix and associated products.
* resolve dependency between options and their prices

[Draft] Catalog storefront, product options and variants management

---

design-documents/graph-ql/coverage/catalog/product-reviews.graphqls

Catalog Product Review GraphQL module with UID changes.
To keep consistency throughout the GraphQL schema, we have replaced the Id field with UID.
@melnikovi @cpartica

product review UID changes

---

design-documents/graph-ql/coverage/customer/customer.graphqls

Customer GraphQL Schema with UID changes.
To keep consistency throughout the GraphQL schema, we have replaced the Id field with Uid.

Customer GraphQL Uid changes

---

design-documents/graph-ql/coverage/returns.graphqls

The returns Customer and comments author have to be modified as we don't need all the customer data.
we can group needed data in a type, and comments don't always have a first name and last name so one author name is enough.

Modifying returns schema for customer and author according to new requirements 

---

design-documents/graph-ql/coverage/b2b/negotiableQuotes.graphqls

We want to inline negotiable quote schema with uids 
replacing wording id with uid and ID type where possible

Add uid where for negotiable quote

---

design-documents/graph-ql/coverage/b2b/negotiableQuotes.graphqls

The existing placeOrder mutation works for Cart, but does not account for Negotiable Quote usage.
Override the mutation to support Negotiable Quotes.
@cpartica

Updated placeOrder mutation for negotiable quote usage
